### ISSUE TITLE
Too much space around the page title

### ISSUE THREAD

**Issue by catalinpit** [catalinpit/attila-theme#2]
There is too much space on pages around the title.

See the image for an example or visit the link [https://catalins.tech/tools-and-services/](https://catalins.tech/tools-and-services/).
<img width="1634" alt="CleanShot 2023-11-23 at 20 34 38@2x" src="https://github.com/catalinpit/attila-theme/assets/25515812/dcf57046-5e63-46de-aee8-e8cbbff8cc55">

This could be improved by updating the following classes:
* `post-header`
* `post-title`

**Comment by Badr-21** [comment]
Hi Catanil, just to be sure, how would you like to improve it? by reducing the space around the title or increasing the font size?

**Comment by catalinpit** [comment]
> Hi Catanil, just to be sure, how would you like to improve it? by reducing the space around the title or increasing the font size?

Hey! Reducing the space around the title (margin and/or padding). See the classes mentioned in the issue. 🙌

**Comment by Badr-21** [comment]
OK, Can you please assign it to me?

**Comment by catalinpit** [comment]
Done, thanks!

**Comment by Badr-21** [comment]
I don't know why I am encountering these errors when running npm install. I updated node, but the error persists
![Screenshot_1](https://github.com/catalinpit/attila-theme/assets/87186226/73adcbeb-b76d-486e-abf7-992716cce10e)

**Comment by 0xSaksham** [comment]
@catalinpit can I try this issue?

**Comment by 0xSaksham** [comment]
@catalinpit I have started working on it

**Comment by catalinpit** [comment]
> @catalinpit I have started working on it

Ok, thanks for the update!

**Comment by catalinpit** [comment]
Hey @0xSaksham are you still working on this? Just want to know before I start working on it. Thanks!
